<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNDhSt7S\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNDhSt7S/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNDhSt7S.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNDhSt7S\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNDhSt7S\App_KernelDevDebugContainer([
    'container.build_hash' => 'NDhSt7S',
    'container.build_id' => '66903614',
    'container.build_time' => 1644710927,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNDhSt7S');
